name: Onda Branca

on:
  push:
    branches: [ main ]

jobs:
  build-angular:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build
