name: Build Angular App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd web/Onda_branca
          npm ci

      - name: Build Angular app
        run: |
          cd web/Onda_branca
          npm run build
      
      - name: Deploy to GitHub Pages
        run: |
          cd web/Onda_branca
          npx angular-cli-ghpages --dir=dist/onda